# General netcdf settings
netcdf:
  filepattern: http://thredds.met.no/thredds/dodsC/meps25files/meps_det_extracted_2_5km_@YYYY@@MM@@DD@T@HH@Z.nc
  offset: 10800
  file_inc: 21600
  fcint: 21600

# General grib1 settings
grib1:
  filepattern:

# General grib2 settings
grib2:
  filepattern:

# Orography
ZS:
  netcdf:
    converter:
      none:
        name: altitude
      phi2m:
        phi:
          name: surface_geopotential
  grib1:

# Reference height Z
ZREF:
  screen:
    netcdf:
    constant:
      value: 10
    grib1:
    constant:
      value: 10
  ml:
    netcdf:
    constant:
      value: 12.5
    grib1:
      converter:
        none:
# Reference height U
UREF:
  screen:
    netcdf:
    constant:
      value: 10
    grib1:
    constant:
      value: 10
  ml:
    netcdf:
    constant:
      value: 12.5
    grib1:
      converter:
        none:

# Temperature
TA:
  screen:
    netcdf:
      converter:
        none:
          name: air_temperature_2m
    grib1:
      converter:
        none:
          parameter: 11
          level: 105
          height: 2
          tri: 0
  ml:
    netcdf:
      converter:
        none:
          name: air_temperature_ml
          level: 0.99851962924
    grib1:
      converter:
        none:
          parameter: 11
          level: 109
          height: 65
          tri: 0
    grib2:
      converter:
        none:
    ascii:
      converter:
        none:


# Specific humidity
QA:
  screen:
    netcdf:
      converter:
        none:
          specific_humidity_2m
        rh2q:
          rh:
            name: relative_humidity_2m
            level: 2
            units: "%"
          t:
            name: air_temperature_2m
            level: 2
            units: "celsius"
          p:
            name: surface_air_pressure
            units: "hPa"
  ml:
    netcdf:
      converter:
        none:
          name: specific_humidity_ml
          level: 0.99851962924
        rh2q:
          rh:
            name: relative_humidity_ml
            level: 0.99851962924
            units: "%"
          t:
            name: air_temperature_ml
            level: 0.99851962924
            units: "celsius"
          p:
            name: surface_air_pressure
            units: "hPa"


# Wind speed
WIND:
  screen:
    netcdf:
      converter:
        none:
          name: wind_speed_10m
        windspeed:
          x:
            name: x_wind_10m
          y:
            name: y_wind_10m
    grib1:
      converter:
        none:
          parameter:
        windspeed:
          x:
          y:

  ml:
    netcdf:
      converter:
        none:
          name: wind_speed_ml
          level: 0.99851962924
        windspeed:
          x:
            name: x_wind_ml
            level: 0.99851962924
          y:
            name: y_wind_ml
            level: 0.99851962924
    grib1:
      converter:
        none:
          parameter:

# Wind direction
WIND_DIR:
  screen:
    netcdf:
      converter:
        none:
          name: wind_direction_10m
        winddir:
          x:
            name: x_wind_10m
          y:
            name: y_wind_10m
    grib1:
      converter:
        none:
          parameter:
        windspeed:
          x:
          y:

  ml:
    netcdf:
      converter:
        none:
          name: wind_direction_ml
          level: 0.99851962924
        winddir:
          x:
            name: x_wind_ml
            level: 0.99851962924
          y:
            name: y_wind_ml
            level: 0.99851962924
    grib1:
      converter:
        none:

# Rainfall rate
RAIN:
  netcdf:
    converter:
      none:
        name: rainfall_amount
        accumulated: False
        instant: 3600.
      totalprec:
        totalprec:
          name: precipitation_amount_acc
          accumulated: True
          instant: 3600.
        snow:
          name: snowfall_amount_acc
          accumulated: True
          instant: 3600.

# Snow fall amount rate
SNOW:
  netcdf:
    converter:
      none:
        name: snowfall_amount_acc
        accumulated: True
        instant: 3600.

# Surface air pressure
PS:
  netcdf:
    converter:
      none:
        name: surface_air_pressure

# Direct shortwave radiation
DIR_SW:
  netcdf:
    converter:
      none:
        name: integral_of_surface_downwelling_shortwave_flux_in_air_wrt_time
        accumulated: True
        instant: 3600.

# Direct scattered radiation
SCA_SW:
  netcdf:
    converter:
      none:
        name: scattered_short_wave_radiation

  constant:
    value: 0

# Long wave radiation
LW:
  netcdf:
    converter:
      none:
        name: integral_of_surface_downwelling_longwave_flux_in_air_wrt_time
        accumulated: True
        instant: 3600.

# Carbon dioxide
CO2:
  netcdf:
    converter:
      none:
        name: carbon_dioxide
  constant:
    value: 0.00062