config_files = ["config_exp.toml", "config_exp_observations.toml", "config_exp_surfex.toml"]

["config_exp.toml"]
blocks = ["GENERAL", "COMPILE", "GEOMETRY", "INITIAL_CONDITIONS", "FORECAST", "SYSTEM"]

["config_exp_observations.toml"]
blocks = ["OBSERVATIONS"]

["config_exp_surfex.toml"]
blocks = ["SURFEX"]

