[OBSERVATIONS]

#OBDIR_PATTERN="$HM_DATA/archive/observations/@YYYY@/@MM@/@DD@/@HH@/"
OBDIR_PATTERN="/tmp/host1/testdata/"

# *** Observation monitoring ***
OBSMONITOR="obstat"                     # Create Observation statistics plots

#---------------------------------------------------
# Observations file
#---------------------------------------------------
OFORMAT="BUFR"    

#---------------------------------------------------
#  TITAN observation settings
#---------------------------------------------------
SYNOP_OBS_T2M=1             # SYNOP 2m air temperature from bufr files
SYNOP_OBS_RH2M=1            # SYNOP 2m relative humidity from bufr files 
SYNOP_OBS_SD=1              # SYNOP snow depth from bufr files
NETATMO_OBS_T2M=1           # 2m air temperature observations from Netatmo stations
NETATMO_OBS_RH2M=1          # 2m relative humidity observations from Netatmo stations
# NETATMO_FILEPATTERN = "@OBDIR_PATTERN@/"
# NETATMO_FILEPATTERN = "/lustre/storeB/project/metproduction/products/netatmo/@YYYY@/@MM@/@DD@/@YYYY@@MM@@DD@T@HH@@mm@01Z.json"
NETATMO_FILEPATTERN = "/tmp/host1/testdata/@YYYY@@MM@@DD@T@HH@@mm@*Z_all.json"

[OBSERVATIONS.QC]
# QC_TESTS = ["domain", "blacklist", "nometa", "redundancy", "plausibility", "sct"]
TESTS = ["domain", "nometa", "plausibility", "sct"]

[OBSERVATIONS.QC.SD]
TESTS = ["domain", "blacklist", "nometa", "plausibility", "firstguess"]


[OBSERVATIONS.OI.T2M]
GRADIENT = -0.0065
HLENGTH = 30000
VLENGTH = 400

[OBSERVATIONS.OI.RH2M]
HLENGTH = 30000
VLENGTH = 400

[OBSERVATIONS.OI.SD]
HLENGTH = 60000
VLENGTH = 300
