[EPS]

[EPS.MEMBER_SETTINGS.GENERAL]
HH_LIST      = { 0 = '0-21:3', 1 = '0-21:3', 2 = '0-21:3' }
LL_LIST      = { 0 = '3',  1 = '3',   2 = '3' }
[EPS.MEMBER_SETTINGS.SURFEX.ASSIM.SCHEMES]
ISBA = {  0 = "OI", 1 = "OI", 2 = "OI" }
[EPS.MEMBER_SETTINGS.SURFEX.SEA]
PERTFLUX  = { 0 = "none" }
[EPS.MEMBER_SETTINGS.SURFEX.ISBA]
PERTSURF = { 0 = "none" }


