# SURFEX offline experiment configuration file
#

[GENERAL]
######################################################################################################
# General (not grouped settings)
######################################################################################################

HH_LIST="00-21:3"                       # Which cycles to run, replaces FCINT
LL_LIST="48,3,3,3,3,3,3,3"              # Forecast lengths for the cycles [h], replaces LL, LLMAIN
                                        # The LL_LIST list is wrapped around if necessary, to fit HH_LIST

[COMPILE]
####################################################################################################
# Compilation settings
#####################################################################################################
BUILD = "yes"                           # Turn on or off the compilation and binary build ( yes|no)


[GEOMETRY]
#####################################################################################################
# Geometry
#####################################################################################################
DOMAIN = "DKCOEXP"                  # See definitions in config/Harmonie_domains.json

[INITIAL_CONDITIONS]
ANASURF = "gridpp"

[FORECAST]
#####################################################################################################
#  Forecast model (physics + dynamics and output)
#####################################################################################################

ENSMSEL = []                            # Ensemble members to run (list with member numbers)

# **** Postprocessing/output ****
TFLAG = "h"                             # Time flag for model output. (h|min)
                                        # h   = hour based output
                                        # min = minute based output

# The unit of should be:
#   - hours   if TFLAG="h"
#   - minutes if TFLAG="min"

# Writeup times of # history,surfex and fullpos files
# Comma separated list, and/or range(s) like:
# t1,t2,t3-t4,t5-t6:step    tb-te == tb-te:1 == tb,tb+1,tb+2,...,te
SFXSELTIMES = "00-60:3"                 # Surfex select file output times
                                        # Only meaningful if SURFEX_LSELECT=yes
SWRITUPTIMES = "00-06:3"                # Surfex model state output times
SFXWFTIMES = "00-06:3"                  # SURFEX history FA file IO server gathering times
SURFEX_LSELECT = "yes"                  # Only write selected fields in surfex outpute files. (yes|no)

[SYSTEM]
