language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
os: linux

before_install:
  - sudo apt-get -y install libudunits2-dev

install:
  pip install -r requirements.txt

# command to run tests
script:
  - wget https://drive.google.com/open?id=1BZCfkop_CLfN2dHjfHpuO4XIz7nfE6Vv -o testdata.tgz
  - tar -xvf testdata.tgz
  - nosetests

# Deploy
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
