
DOMAIN = "NORWAY_SOUTH"
MODIFY_LAKES = ".FALSE"             # Use Vanern/Vattern as Sea, requires new upper air climate files: ".FALSE."|".TRUE."
TIME_STEP = 60

###################
# SURFEX SETTINGS #
###################


#####################################
# IO and non-tile specific settings #
#####################################
# SURFEX IO
[SURFEX_IO]
CSURF_FILETYPE = "FA"               # IO settings NC/FA/ASCII. Inline runs use FA
CTIMESERIES_FILETYPE = "FA"         # Fileformat for timseries. Inline runs use FA
CFORCING_FILETYPE = "NETCDF"        # Offline surfex forcing format (NETCDF/ASCII)
XTSTEP = 600                        # Surfex time step (Only used in the binary OFFLINE)
XTSTEP_OUTPUT = 21600.0             # Output interval from the binary OFFLINE
LSPLIT_PATCH = true                 # Split patches into separate variables in output files

[COVER]                             # Land cover information
YCOVER = "ECOCLIMAP_2_5_p.dir"      # Version of ECOCLIMAP for surfex (1,2,SG)
                                    # Available versions are 1.1-1.5,2.0-2.2.1,SG and 2.5_plus if you use FLake
                                    # SG represents SecondGeneration and is now availbale for tests on ECMWF. However,
                                    # please note that SG is not yet compatible with any availbale lake data base.

[ZS]                                # Orography
YZS = "gtopo30.dir"                 # Database with orography: "gmted2010"|"gtopo30"

[PARAMETERS]
XRIMAX = 0.2                        # Maximum allowed Richardson number in the surface layer

[SURFEX_TILES]                      # Define which tile schemes to use
SEA = "SEAFLX"                      # Sea scheme
INLAND_WATER = "FLAKE"              # Treatment of lakes in surfex (WATFLX|FLAKE)
NATURE = "ISBA"                     # Nature scheme: "ISBA"|"NONE"
TOWN = "TEB"                        # Town scheme: "TEB"|"NONE"

#########################################
########## Tile specific settings #######
#########################################

#######
# SEA #
#######
[SEA]                               # General sea settings
SEA_ICE = "NONE"                    # Treatment of sea ice in surfex (NONE|SICE)
PERTURB_FLUXES = false              # Perturb sea fluxes

################
# INLAND WATER #
################

# General inland water
[INLAND_WATER]

# General FLAKE
[FLAKE]
LCLIM = true                        # Use FLAKE climatology

##########
# NATURE #
##########

# ISBA settings
[ISBA]
SCHEME = "3-L"                      # Type of ISBA scheme in SURFEX. Options: "3-L"|"2-L"|"DIF"
NPATCH = 2                          # Number of patches over land in SURFEX (see also LISBA_CANOPY)
MEB = false                         # Enable Multi Energy Budget (MEB) model
CANOPY = false                      # Activates surface boundary multi layer scheme over land in SURFEX
                                    # (must be false for NPATCH>1)
SNOW = "D95"                        # Type of snow scheme in SURFEX. Options: "D95" and "3-L"
YSOC_TOP = "soc_top.dir"            # Soil organic carbon data. Options: "soc_top.dir"
YSOC_SUB = "soc_sub.dir"            # Soil organic carbon data. Options: "soc_sub.dir"

YSAND = "sand_fao.dir"              # Soil texture input data: "sand_fao.dir"|"SAND_HWSD_MOY_V2.dir"|"sand_SOILGRID.dir"
                                    # suffix json assumes namelist values provided as a json file

YCLAY = "clay_fao.dir"              # Soil texture input data: "clay_fao.dir"|"CLAY_HWSD_MOY_V2.dir"|"clay_SOILGRID.dir"
                                    # suffix json assumes namelist values provided as a json file
PERTSURF = false                    # Perturb surface parameters

# Sub-grid-scale orography settings
[SSO]
SCHEME = "NONE"                     # SSO scheme used in SURFEX "NONE"|"'Z01D'"|"'BE04'"|"'OROT'"

# Tree height treatment
[TREEDRAG]
TREEDATA_FILE = ""                  # Name of tree height data file (with *.llv suffix)
XSCALE_H_TREE = 1.0                 # Scale the tree height with this factor

########
# TOWN #
########
# Settings for town tile.
[TOWN]
LTOWN_TO_ROCK = false               # Switch to set town as rock. Only used if surfex tile scheme for town is "NONE".
                                    # If true will override other TOWN scheme settings and set CTOWN == "NONE"

# TEB specific settings
[TEB]


#########################
# Assimilation settings #
#########################

[ASSIM]
SPATIALIZATION_TOOL = "CANARI"       # Program which does horizontal analysis: "gridpp"|"CANARI"
ASSIMILATION_TOOL = "CANARI"         # Program which updates the soil: "SODA"|"CANARI".
CFILE_FORMAT_LSM = "FA"              # File format for land sea mask when using SODA: "ASCII"|"FA"

[ASSIM_SCHEMES]
SEA = "INPUT"                        # Assimilation method for sea tile: "INPUT"|"NONE"
INLAND_WATER = "INPUT"               # Assimilation method for water tile: "INPUT"|"NONE"
ISBA = "OI"                          # Assimilation method for ISBA soil: "NONE"|"OI"|"EKF"
TEB = "ROADT"                        # Assimilation method for TEB tile: "NONE"|"ROADT"

[ASSIM_OBS]
LOBSHEADER = false                          # ASCII observation file has header
CFILE_FORMAT_OBS = "ASCII"                  # File format for observations when using SODA: "ASCII"|"FA"
LOBSNAT = false                             # Observation ASCII file only contains nature points
NNCO = [1, 1, 0, 0, 1]                      # Active observation types
                                            # (Element 1=T2m, element 2=RH2m and element 3=Soil moisture, element 5=SWE)
XERROBS_M = [1.0, 0.1, 0.1, 0.1, 0.1, 20.0] # Observation error (used in EKF)
LSWE = false                                # Assimilate SWE, if false assimilate snow depth

[ASSIM_SEA]
CFILE_FORMAT_SST = "FA"              # File format for SST input when using SODA and SEA == "INPUT": "ASCII"|"FA"
LREAD_SST_FROM_FILE = true           # When SEA == INPUT read SST from external file
LEXTRAP_SEA = false                  # Extrapolate sea variables to points having LSM < 0.5

[ASSIM_INLAND_WATER]
LWATERTG2 = false                    # Use TG2 as LST in points having both land and water defined. Should use LEXTRAP_WATER=true
LEXTRAP_WATER = false                # Extrapolate LST to points having LSM < 0.5 or to points masked by LWATERTG2

[ASSIM_ISBA]
UPDATE_SNOW_CYCLES = ["06"]          # Cycles to update snow depths/SWE in assimilation.
                                     # Empty list or not valid values means no update

# OI settings
[ASSIM_ISBA_OI]
CFILE_FORMAT_CLIM = "FA"            # File format for file containing climatological fields
CFILE_FORMAT_FG = "FA"              # File format of upper air first guess
ANASURF_OI_COEFF="POLYNOMES_ISBA"    # Specify use of OI coefficients file (POLYNOMES_ISBA|POLYNOMES_ISBA_MF6)
                                     # POLYNOMES_ISBA_MF6 means 6 times smaller coefficients for WG2 increments

# EKF settings
[ASSIM_ISBA_EKF]
NNCV = [0,1,0,1]                        # Active EKF control variables. 1=WG2 2=WG1 3=TG2 4=TG1
XSIGMA_M = [2.0, 2.0, 0.1 , 0.15]       # Background error
CVAR_M = ["TG1", "TG2", "WG1" , "WG2"]  # Control variables
XPRT_M = [0.0001, 0.0001, 1e-05, 1e-05] # Perturbation magnitude
XSCALE_Q = 0.125                        # Scaling of obs error
EVOLVE_B = false                        # Evolve B matrix each cycle
