
###################
# SURFEX SETTINGS #
###################


#####################################
# IO and non-tile specific settings #
#####################################
# SURFEX IO
[SURFEX_IO]
CSURF_FILETYPE = "NC"               # IO settings NC/FA/ASCII. Inline runs use FA
CTIMESERIES_FILETYPE = "NC"         # Fileformat for timseries. Inline runs use FA
CFORCING_FILETYPE = "NETCDF"        # Offline surfex forcing format (NETCDF/ASCII)
XTSTEP = 60                         # Surfex time step (Only used in the binary OFFLINE)
XTSTEP_OUTPUT = 3600.0              # Output interval from the binary OFFLINE
LSPLIT_PATCH = true                 # Split patches into separate variables in output files


##########
# NATURE #
##########

# ISBA settings
[ISBA]
SCHEME = "DIF"                      # Type of ISBA scheme in SURFEX. Options: "3-L"|"2-L"|"DIF"
NPATCH = 2                          # Number of patches over land in SURFEX (see also LISBA_CANOPY)
MEB = true                          # Enable Multi Energy Budget (MEB) model
CANOPY = false                      # Activates surface boundary multi layer scheme over land in SURFEX
                                    # (must be false for NPATCH>1)
SNOW = "3-L"                        # Type of snow scheme in SURFEX. Options: "D95" and "3-L"


#########################
# Assimilation settings #
#########################

[ASSIM]
SPATIALIZATION_TOOL = "gridpp"       # Program which does horizontal analysis: "gridpp"|"CANARI"
ASSIMILATION_TOOL = "SODA"           # Program which updates the soil: "SODA"|"CANARI".
CFILE_FORMAT_LSM = "ASCII"           # File format for land sea mask when using SODA: "ASCII"|"FA"

[ASSIM_SCHEMES]
SEA = "NONE"                         # Assimilation method for sea tile: "INPUT"|"NONE"
INLAND_WATER = "NONE"                # Assimilation method for water tile: "INPUT"|"NONE"
ISBA = "EKF"                         # Assimilation method for ISBA soil: "NONE"|"OI"|"EKF"
TEB = "NONE"                         # Assimilation method for TEB tile: "NONE"|"ROADT"

[ASSIM_OBS]
LOBSHEADER = false                          # ASCII observation file has header
CFILE_FORMAT_OBS = "ASCII"                  # File format for observations when using SODA: "ASCII"|"FA"
LOBSNAT = false                             # Observation ASCII file only contains nature points
NNCO = [0, 0, 0, 0, 0]                      # Active observation types
                                            # (Element 1=T2m, element 2=RH2m and element 3=Soil moisture, element 5=SWE)
XERROBS_M = [1.0, 0.1, 0.1, 0.1, 0.1, 20.0] # Observation error (used in EKF)
LSWE = false                                # Assimilate SWE, if false assimilate snow depth

[ASSIM_ISBA]
UPDATE_SNOW_CYCLES = ["06"]          # Cycles to update snow depths/SWE in assimilation.
                                     # Empty list or not valid values means no update

# EKF settings
[ASSIM_ISBA_EKF]
NNCV = [0,0,0,0]                        # Active EKF control variables. 1=WG2 2=WG1 3=TG2 4=TG1
XSIGMA_M = [2.0, 2.0, 0.1 , 0.15]       # Background error
CVAR_M = ["TG1", "TG2", "WG1" , "WG2"]  # Control variables
XPRT_M = [0.0001, 0.0001, 1e-05, 1e-05] # Perturbation magnitude
XSCALE_Q = 0.125                        # Scaling of obs error
EVOLVE_B = false                        # Evolve B matrix each cycle