
#####################################
# IO and non-tile specific settings #
#####################################
# SURFEX IO
[SURFEX_IO]
CSURF_FILETYPE = "NC"               # IO settings NC/FA/ASCII. Inline runs use FA
CTIMESERIES_FILETYPE = "NC"         # Fileformat for timseries. Inline runs use FA

#########################
# Assimilation settings #
#########################

[ASSIM]
SPATIALIZATION_TOOL = "gridpp"       # Program which does horizontal analysis: "gridpp"|"CANARI"
ASSIMILATION_TOOL = "SODA"           # Program which updates the soil: "SODA"|"CANARI".
CFILE_FORMAT_LSM = "ASCII"           # File format for land sea mask when using SODA: "ASCII"|"FA"

[ASSIM_OBS]
CFILE_FORMAT_OBS = "ASCII"           # File format for observations when using SODA: "ASCII"|"FA"
LSWE = false                         # Assimilate SWE, if false assimilate snow depth

[ASSIM_SEA]
CFILE_FORMAT_SST = "ASCII"

# OI settings
[ASSIM_ISBA_OI]
CFILE_FORMAT_CLIM = "ASCII"          # File format for file containing climatological fields
CFILE_FORMAT_FG = "ASCII"            # File format of upper air first guess