# IO settings
[io]
CSURF_FILETYPE = "NC"

[pgd]
CISBA = "3-L"
NPATCH = "3"

[prep]

[offline]

[soda]
[assimilation]
LASSIM = false
CASSIM_SEA = "INPUT"
CASSIM_ISBA = "EKF"

[observations]
SPATIALIZATION_TOOL = "gridpp"
CFILE_FORMAT_OBS = "ASCII"
