
DOMAIN = "NORWAY_SOUTH"
MODIFY_LAKES = ".FALSE"             # Use Vanern/Vattern as Sea, requires new upper air climate files: ".FALSE."|".TRUE."

###################
# SURFEX SETTINGS #
###################

###############################
# System specific input data. #
###############################

# Paths must be set in the system json file for your platform
[DIRECT_INPUT_DATA_ISBA]
YSAND = "FAO_SAND"                  # Soil texture input data "FAO"|"HWSD_v2"|"SOILGRID"
YCLAY = "FAO_CLAY"                  # Soil texture input data "FAO"|"HWSD_v2"|"SOILGRID"
YSOC_TOP = "SOC_TOP"                # Soil organic carbon data
YSOC_SUB = "SOC_SUB"                # Soil organic carbon data

[DIRECT_INPUT_DATA_ZS]
YZS = "gmted2010"                    # Database with orography: "gmted"|"gtopo"

[DIRECT_INPUT_DATA_COVER]
YCOVER = "ecoclimap_2_5_plus"       # Version of ECOCLIMAP for surfex (1,2,SG)
                                    # Available versions are 1.1-1.5,2.0-2.2.1,SG and 2.5_plus if you use FLake
                                    # SG represents SecondGeneration and is now availbale for tests on ECMWF. However,
                                    # please note that SG is not yet compatible with any availbale lake data base.

[DIRECT_INPUT_DATA_FLAKE]
LAKE_DEPTH = "GlobalLakeDepth"      # Lake depth database
LAKE_STATUS = "GlobalLakeStatus"    # Lake status database

# Input data in the LLV format
[LLV_INPUT_DATA_TREE_HEIGHT]
H_TREE_FILE = "H_TREE_FILE"         # LLV file with external tree height data

# Input data in NetCDF format
[NC_INPUT_DATA_FLAKE]
LAKE_CLIM = "LAKE_LTA_NEW.nc"       # Lake climatology needed in PREP

#################
# Configuration #
#################

# SURFEX IO
[SURFEX_IO]
CSURF_FILETYPE = "NC"               # IO settings NC/FA/ASCII
CFORCING_FILETYPE="NETCDF"          # Offline surfex forcing format (NETCDF/ASCII)


[PARAMETERS]
XRIMAX = 0.0                        # Maximum allowed Richardson number in the surface layer

# Define which tile schemes to use
[SURFEX_TILES]
SEA = "SEAFLX"                      # Sea scheme
INLAND_WATER = "FLAKE"              # Treatment of lakes in surfex (WATFLX|FLAKE)
NATURE = "ISBA"                     # Nature scheme: "ISBA"|"NONE"
TOWN = "TEB"                        # Town scheme: "TEB"|"NONE"


# Tile specific settings
##############################

# General sea settings
[SEA]
SEA_ICE = "SICE"                    # Treatment of sea ice in surfex (NONE|SICE)

# General inland water
[INLAND_WATER]

# General FLAKE
[FLAKE]
LCLIM = true                        # Use FLAKE climatology

# ISBA settings
[ISBA]
SCHEME = "3-L"                      # Type of ISBA scheme in SURFEX. Options: "3-L"|"2-L"|"DIF"
NPATCH = 2                          # Number of patches over land in SURFEX (see also LISBA_CANOPY)
CANOPY = false                      # Activates surface boundary multi layer scheme over land in SURFEX
                                    # (must be false for NPATCH>1)
SNOW = "D95"                        # Type of snow scheme in SURFEX. Options: "D95" and "3-L"

# Sub-grid-scale orography settings
[ROUGHNESS]
SCHEME = "NONE"                     # SSO scheme used in SURFEX "NONE"|"'Z01D'"|"'BE04'"|"'OROT'"

# Tree height treatment
[TREEDRAG]
XSCALE_H_TREE = 1.0                 # Scale the tree height with this factor

# Settings for town tile.
[TOWN]
LTOWN_TO_ROCK = false               # Switch to set town as rock. Only used if surfex tile scheme for town is "NONE".

# TEB specific settings
[TEB]


#########################
# Assimilation settings #
#########################

[ASSIM]
SPATIALIZATION_TOOL = "gridpp"       # Program which does horizontal analysis: "gridpp"|"CANARI"
ASSIMILATION_TOOL = "SODA"           # Program which updates the soil: "SODA"|"CANARI".
CFILE_FORMAT_LSM = "ASCII"           # File format for land sea mask when using SODA: "ASCII"|"FA"

[ASSIM_SCHEMES]
SEA = "INPUT"                        # Assimilation method for sea tile: "INPUT"|"NONE"
INLAND_WATER = "INPUT"               # Assimilation method for water tile: "INPUT"|"NONE"
ISBA = "EKF"                         # Assimilation method for ISBA soil: "NONE"|"OI"|"EKF"
TEB = "ROADT"                        # Assimilation method for TEB tile: "NONE"|"ROADT"

[ASSIM_OBS]
LOBSHEADER = false
CFILE_FORMAT_OBS = "ASCII"           # File format for observations when using SODA: "ASCII"|"FA"
LOBSNAT = false
COBS_M = [1, 1, 0, 0, 1]             # Active observation types
                                     # (Element 1=T2m, element 2=RH2m and element 3=Soil moisture, element 5=SWE)

XERROBS_M = [1.0, 0.1, 0.1, 0.1, 0.1, 20.0]
LSWE = false


[ASSIM_SEA]
CFILE_FORMAT_SST = "ASCII"           # File format for SST input when using SODA and SEA == "INPUT": "ASCII"|"FA"
LREAD_SST_FROM_FILE = true           # When SEA == INPUT read SST from external file

[ASSIM_INLAND_WATER]
LWATER_TG2 = false

[ASSIM_ISBA]
UPDATE_SNOW_CYCLES = ["06"]         # Cycles to update snow depths/SWE in assimilation.
                                    # Empty list or not valid values means no update

# OI settings
[ASSIM_ISBA_OI]
CFILE_FORMAT_CLIM = "ASCII"
CFILE_FORMAT_FG = "ASCII"

[ASSIM_ISBA_OI_INPUT]
ANASURF_OI_COEFF="POLYNOMES_ISBA"   # Specify use of OI coefficients file (POLYNOMES_ISBA|POLYNOMES_ISBA_MF6)
                                    # POLYNOMES_ISBA_MF6 means 6 times smaller coefficients for WG2 increments

# EKF settings
[ASSIM_EKF]
NNCV = [1,1,1,1]                    # Active EKF control variables. 1=WG2 2=WG1 3=TG2 4=TG1
XSIGMA_M = [0.1, 0.1, 1.0 , 1.0]    # Background error
