#
# HARMONIE system configuration unitTest emulating dual host setup
#

[HOST_SYSTEM]

# Define computer centre.
COMPCENTRE="LOCAL"

# Define hosts
HOSTS = ["my_host_0", "my_host_1"]

# Location of working data, fast and large system
# Experiment identifier and directories
# EXP is defined when an experiment is started by "Harmonie start ..."
SFX_EXP_DATA = "/tmp/host0/scratch/hm_home/$EXP"	# HM_DATA on main HIRLAM host
# directory for scripts, compiled objects, executables
SFX_EXP_LIB = "/tmp/host0/scratch/hm_home/$EXP/lib"
HOST_NAME = ""
ECF_HOST = "pc4384"
ECF_LOGHOST = "pc4384"
JOBOUTDIR = "/tmp/host0/job"
HM_CS = "gfortran"
PARCH = ""
MKDIR = "mkdir -p"
RSYNC = "rsync -avh"
SURFEX_CONFIG = "my_harmonie_config"

[HOST_SYSTEM.HOST1]
HOST_NAME = "saints"
SFX_EXP_DATA = "/tmp/host1/scratch/hm_home/$EXP"       # HM_DATA on main HIRLAM host
SFX_EXP_LIB = "/tmp/host1/scratch/hm_home/$EXP/lib"
# directory for scripts, compiled objects, executables
ECF_HOST = "ecf_host1"
ECF_LOGHOST = "ecf_host1"
JOBOUTDIR = "/tmp/host1/job"


