
###################
# Quality Control #
###################

[QualityControl]
tests = ["Plausibility"]

[QualityControl.t2m]
output = "@ARCHIVE_PATTERN@/qc_t2m.json"
netatmo_filepattern = "@HOME@/hm_home/sandbox/netatmo/@YYYY@/@MM@/@DD@/@YYYY@@MM@@DD@T@HH@@mm@01Z.json"

[QualityControl.rh2m]
output = "@ARCHIVE_PATTERN@/qc_rh.json"
netatmo_filepattern = "@HOME@/hm_home/sandbox/netatmo/@YYYY@/@MM@/@DD@/@YYYY@@MM@@DD@T@HH@@mm@01Z.json"

[QualityControl.sd]
# tests = "Plausibility FirstGuess"
output = "@ARCHIVE_PATTERN@/qc_sd.json"
tests = ""
