[OBSERVATIONS]

OBDIR_PATTERN="$HM_DATA/archive/observations/@YYYY@/@MM@/@DD@/@HH@/"

# *** Observation monitoring ***
OBSMONITOR="obstat"                     # Create Observation statistics plots

#---------------------------------------------------
# Observations file
#---------------------------------------------------
OFORMAT="BUFR"    

#---------------------------------------------------
#  TITAN observation settings
#---------------------------------------------------
SYNOP_OBS_T2M=1             # SYNOP 2m air temperature from bufr files
SYNOP_OBS_RH2M=1            # SYNOP 2m relative humidity from bufr files 
SYNOP_OBS_SD=1              # SYNOP snow depth from bufr files
NETATMO_OBS_T2M=1           # 2m air temperature observations from Netatmo stations
NETATMO_OBS_RH2M=1          # 2m relative humidity observations from Netatmo stations
QC_TESTS="domain blacklist nometa redundancy plausibility firstguess sct"

