#
# system configuration unitTest emulating dual host setup
#

[HOST_SYSTEM]

# Define computer centre.
COMPCENTRE="LOCAL"

# Define hosts
HOSTS = ["my_host_0", "my_host_1"]

SFX_EXP_DATA = "/tmp/host0/scratch/hm_home/$EXP"
SFX_EXP_LIB = "/tmp/host0/scratch/hm_home/$EXP/lib"
HOST_NAME = ""
JOBOUTDIR = "/tmp/host0/job"
HM_CS = "gfortran"
PARCH = ""
MKDIR = "mkdir -p"
RSYNC = "rsync -avh -e \"ssh -i ~/.ssh/id_rsa\""
SURFEX_CONFIG = "my_harmonie_config"

[HOST_SYSTEM.HOST1]
HOST_NAME = "localhost"
SFX_EXP_DATA = "/tmp/host1/scratch/hm_home/$EXP"
SFX_EXP_LIB = "/tmp/host1/scratch/hm_home/$EXP/lib"
JOBOUTDIR = "/tmp/host1/job"
